version: "3.8"

services:
  superset:
    build: .
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=ENTER_KEY_HERE
    ports:
      - 8088:8088
    volumes:
      - superset_home:/app/superset_home
    command:
      ["/usr/bin/bash", "-c", "superset db upgrade && superset fab create-admin --username admin --firstname Admin --lastname User --email admin@admin.com --password admin && superset init && superset run -h 0.0.0.0 -p 8088"]

volumes:
  superset_home:
